#!/usr/bin/python

class Menu:
    def __init__(self):
        self.options = []
    
    def add_option(self, option):
        self.options.append(option)
    
    def display_options(self):
        print("Please choose an option:")
        for i, option in enumerate(self.options):
            print(f"{i + 1}. {option}")
    
    def get_choice(self):
        choice = input("Enter your choice: ")
        try:
            choice = int(choice)
        except ValueError:
            return None
        if choice < 1 or choice > len(self.options):
            return None
        return choice
