#!/usr/bin/python3

# lowercase - remaps directories and files to kebab-case
# kebab-case was chosen as it is not commonly associated with
# programming languages, so linux filesystem organising seems nice
# intent is to simplify and codify filesystem navigation

import os
import sys

def rename_all(directory):
  # rename root directory
  new_name = directory.strip().lower().replace(" ", "-").replace("_", "-")
  os.rename(directory, new_name)
  directory = new_name
  # iterate through all 1 level of subdirectories and files
  # TODO: implement recursion for full traversal
  for dirpath, dirnames, filenames in os.walk(directory):
    for dirname in dirnames:
      old_name = os.path.join(dirpath, dirname)
      new_name = os.path.join(dirpath, dirname.strip().lower().replace(" ", "-").replace("_", "-"))
      os.rename(old_name, new_name)
    for filename in filenames:
      old_name = os.path.join(dirpath, filename)
      base, ext = os.path.splitext(filename)
      new_name = os.path.join(dirpath, base.strip().lower().replace(" ", "-").replace("_", "-") + ext)
      os.rename(old_name, new_name)

if __name__ == '__main__':
  if len(sys.argv) < 2:
    print("Usage: lowercase <directory>")
    sys.exit()
  directory = sys.argv[1]
  rename_all(directory)

