#!/bin/bash

# pretty-ai is a tool to allow users to easily communicate with the openai

prompt=""
ai="https://api.openai.com/v1/completions"

if [ $# -ne 2 ]; then
    echo "Usage: $0 <api_key_file> <output_file>"
    exit 1
fi

api_key_file=$1
output_file=$2
api_key=$(cat $api_key_file)

curl $ai \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $api_key" \
-d "{\"model\": \"text-davinci-003\", \"prompt\": \"$prompt\", \"temperature\": 0, \"max_tokens\": 7}" \
-o $output_file

# Use jq to extract the text field and store it in a variable
text=$(jq -r '.choices[0].text' $output_file)

# Use jq to extract all other fields and store them in variables
id=$(jq -r '.id' $output_file)
object=$(jq -r '.object' $output_file)
created=$(jq -r '.created' $output_file)
model=$(jq -r '.model' $output_file)
prompt_tokens=$(jq -r '.usage.prompt_tokens' $output_file)
completion_tokens=$(jq -r '.usage.completion_tokens' $output_file)
total_tokens=$(jq -r '.usage.total_tokens' $output_file)
pretty_output_file="$output_file.txt"

# Print the extracted fields with newlines
{
echo "id: $id"
echo "object: $object"
echo "created: $created"
echo "model: $model"
echo
echo "************************************************** "
echo "                     __  __                    _   "
echo "    ____  ________  / /_/ /___  __      ____ _(_)  "
echo     / __ \/ ___/ _ \/ __/ __/ / / /_____/ __ `/ / 
echo "  / /_/ / /  /  __/ /_/ /_/ /_/ /_____/ /_/ / /    "
echo " / .___/_/   \___/\__/\__/\__, /      \__,_/_/     "
echo "/_/                      /____/                    "
echo "                                                   "
echo "************************************************** "
echo 
echo "text: $text"
echo
echo "************************************************** "
echo "                     __  __                    _   "
echo "    ____  ________  / /_/ /___  __      ____ _(_)  "
echo     / __ \/ ___/ _ \/ __/ __/ / / /_____/ __ `/ / 
echo "  / /_/ / /  /  __/ /_/ /_/ /_/ /_____/ /_/ / /    "
echo " / .___/_/   \___/\__/\__/\__, /      \__,_/_/     "
echo "/_/                      /____/                    "
echo "                                                   "
echo "************************************************** "
echo
echo "usage:"
echo "  prompt_tokens: $prompt_tokens"
echo "  completion_tokens: $completion_tokens"
echo "  total_tokens: $total_tokens"
} > $pretty_output_file
