#!/bin/bash

# prompt - changes the default prompt to my personal preference
# day of week, month, datetime DD:HH:MM:SS [number of files in pwd] (green)
# stdin/stdout/stderr (purple)
# adds purple output to shell commands (ls)
# need refinements on fi colours

export PS1="\033[0;32m\]\d:\t [\$(ls | wc -l)]:\$ \033[0;35m\]"
LS_COLORS=$LS_COLORS:'fi=0;35':'di=1;35' ; export LS_COLORS
