#!/bin/bash

# timer for multitasking
# change x to the desired number of minutes to count down from or
# define y and set a timer for a specific time of day based on your
# regional settings

function usage {
  echo "Usage: $0 [OPTION]..."
  echo "Set a timer for x minutes or a specific time and display a message."
  echo ""
  echo "  -x MINUTES       set timer for MINUTES"
  echo "  -y TIME          set timer for specific TIME in format 'HH:MM'"
  echo "  -m MESSAGE       set message to display"
  echo "  --help           display this help and exit"
  echo ""
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    -x) x="$2"; shift 2;;
    -y) y="$2"; shift 2;;
    -m) message="$2"; shift 2;;
    --help) usage;;
    *) break;;
  esac
done

if [[ -z "$x" && -z "$y" ]]; then
  usage
fi

if [[ -n "$y" ]]; then
  time="$y"
  y=$(date +%s --date="$time")
else
  y=$(date +%s --date="23:59")
  time="23:59"
fi

current=$(date +%s)

sleep $((y-current))

gnome-terminal --command "echo '$message'; read"
